
/*
********************************************************
*Criado por Bruno de Sousa Silva entre 07/04/2023 e 12/04/2023
*
********************************************************
*/


USE MASTER
GO

IF EXISTS((select name from sys.sysdatabases WHERE name = 'dbCadastroFuncionarios'))
BEGIN
	DROP DATABASE dbCadastroFuncionarios
	PRINT('Executou DROP DATABASE dbCadastroFuncionarios')
END
GO

--CRIAÇÃO DE BANCO E DAS TABELAS

CREATE DATABASE dbCadastroFuncionarios
GO

USE dbCadastroFuncionarios
GO

CREATE TABLE [dbo].[tbNivelCargo]
(
	NIC_ID INT NOT NULL,
	NIC_DESCRICAO varchar(255) NOT NULL,
	CONSTRAINT PK_tbNivelCargo_NIC_ID PRIMARY KEY CLUSTERED (NIC_ID)
)
GO

CREATE TABLE [dbo].[tbSetor]
(
	STR_ID INT NOT NULL,
	STR_DESCRICAO varchar(255) NOT NULL,
	CONSTRAINT PK_tbNivelCargo_STR_ID PRIMARY KEY CLUSTERED (STR_ID)
)
GO

CREATE TABLE [dbo].[tbPerfilUsuario]
(
	PFU_ID INT NOT NULL,
	PFU_DESCRICAO varchar(255) NOT NULL,
	CONSTRAINT PK_tbNivelCargo_PFU_ID PRIMARY KEY CLUSTERED (PFU_ID)
)
GO

CREATE TABLE [dbo].[tbUsuario]
(
	USU_ID INT IDENTITY (1,1) NOT NULL,
	USU_LOGIN VARCHAR(255) NOT NULL,
	USU_SENHA VARBINARY(256) NOT NULL,
	FUN_ID INT NOT NULL,
	PFU_ID INT NOT NULL

	CONSTRAINT PK_tbNivelCargo_USU_ID PRIMARY KEY CLUSTERED (USU_ID),
	CONSTRAINT FK_tbNivelCargo_tbPerfilUsuario FOREIGN KEY (PFU_ID)
        REFERENCES tbPerfilUsuario (PFU_ID)
)
GO

CREATE TABLE [dbo].[tbFuncionario]
(
	FUN_ID INT IDENTITY (1,1) NOT NULL,
	FUN_NOME VARCHAR(MAX) NOT NULL,
	FUN_CARGO VARCHAR(MAX) NOT NULL,
	FUN_DATA_ADMISSAO DATETIME NOT NULL,
	FUN_CPF VARCHAR(20) NOT NULL,
	FUN_SALARIO DECIMAL(10,2) NOT NULL,
	NIC_ID INT NOT NULL,
	STR_ID INT NOT NULL,	

	CONSTRAINT PK_tbNivelCargo_FUN_ID PRIMARY KEY CLUSTERED (FUN_ID),
	CONSTRAINT FK_tbNivelCargo_tbNivelCargo FOREIGN KEY (NIC_ID) REFERENCES tbNivelCargo (NIC_ID),
	CONSTRAINT FK_tbNivelCargo_tbSetor FOREIGN KEY (STR_ID) REFERENCES tbSetor (STR_ID),	
)
GO

--CRIA PROCEDURES E OUTRAS OPERAÇÕES TRANSACT-SQL POSSÍVEIS


CREATE or ALTER PROCEDURE spListagem
(
	@TABELA VARCHAR(MAX),
	@ORDEM VARCHAR(MAX))
AS
BEGIN
	EXEC('SELECT * FROM ' + @TABELA +
	' ORDER BY ' + @ORDEM)
END
GO

--Procedure para Deletar registros
CREATE OR ALTER PROCEDURE spDelete
(
	@ID_VALOR INT ,
	@ID_PARAMETRO VARCHAR(50),
	@TABELA VARCHAR(MAX)
)
AS
BEGIN
	DECLARE @SQL VARCHAR(MAX);
	DECLARE @FILTRO VARCHAR(MAX) = CONCAT(@ID_PARAMETRO,' = ', cast(@ID_VALOR as varchar(max)));	
	SET @SQL = ' DELETE ' + @TABELA + ' WHERE ' + @FILTRO;
	EXEC(@SQL)
END
GO

---Inserir Funcionario
CREATE OR ALTER PROCEDURE spInsertFuncionario
(	@FUN_ID INT,
	@FUN_NOME VARCHAR(MAX),
	@FUN_CARGO VARCHAR(MAX),
	@FUN_DATA_ADMISSAO DATETIME,
	@FUN_CPF VARCHAR(20),
	@FUN_SALARIO DECIMAL(10,2),
	@NIC_ID INT,
	@STR_ID INT
)
AS
BEGIN
	INSERT INTO tbFuncionario (FUN_NOME, FUN_CARGO, FUN_DATA_ADMISSAO, FUN_CPF, FUN_SALARIO, NIC_ID, STR_ID) 
	VALUES (@FUN_NOME, @FUN_CARGO, @FUN_DATA_ADMISSAO, @FUN_CPF, @FUN_SALARIO, @NIC_ID, @STR_ID)
END
GO

---Update Funcionario
CREATE OR ALTER PROCEDURE spUpdateFuncionario
(	@FUN_ID INT,
	@FUN_NOME VARCHAR(MAX),
	@FUN_CARGO VARCHAR(MAX),
	@FUN_DATA_ADMISSAO DATETIME,
	@FUN_CPF VARCHAR(20),
	@FUN_SALARIO DECIMAL(10,2),
	@NIC_ID INT,
	@STR_ID INT
)
AS
BEGIN
	UPDATE tbFuncionario SET 
	FUN_NOME = @FUN_NOME, 
	FUN_CARGO = @FUN_CARGO, 
	FUN_DATA_ADMISSAO = @FUN_DATA_ADMISSAO, 
	FUN_CPF = @FUN_CPF, 
	FUN_SALARIO = @FUN_SALARIO, 
	NIC_ID = @NIC_ID, 
	STR_ID = @STR_ID
	WHERE FUN_ID = @FUN_ID

END
GO

---Inserir Usuario
CREATE OR ALTER PROCEDURE spInsertUsuario
(
	@USU_ID INT,
	@USU_LOGIN VARCHAR(255),
	@USU_SENHA VARCHAR(20),
	@PFU_ID INT,
	@FUN_ID INT
)
AS
BEGIN
	DECLARE @SENHA_CRIPTO_BANCO VARBINARY(256) 
	SET @SENHA_CRIPTO_BANCO = HASHBYTES('SHA2_256', CONVERT(varbinary(256), CAST(@USU_SENHA AS binary(8))))
	
	INSERT INTO tbUsuario(USU_LOGIN, USU_SENHA, PFU_ID, FUN_ID) VALUES (@USU_LOGIN, @SENHA_CRIPTO_BANCO,@PFU_ID, @FUN_ID)
END
GO

--VALIDAR USUÁRIO
CREATE OR ALTER PROCEDURE spValidaUsuario
(
	@USU_LOGIN VARCHAR(255),
	@USU_SENHA VARCHAR(20)
)
AS
BEGIN
	DECLARE @SENHA_CRIPTO_DIGITADA VARBINARY(256)
	SET @SENHA_CRIPTO_DIGITADA = HASHBYTES('SHA2_256', CONVERT(varbinary(256), CAST(@USU_SENHA AS binary(8))))

	DECLARE @RETORNO INT
	DECLARE @TESTE_LOGIN INT = (SELECT COUNT(USU_LOGIN) FROM tbUsuario WHERE USU_LOGIN = @USU_LOGIN)
	DECLARE @TESTE_SENHA INT 

		IF(@TESTE_LOGIN = 0)
		BEGIN
			SET @RETORNO = -1
		END
		ELSE 
		BEGIN
			SET @TESTE_SENHA = (SELECT COUNT(USU_SENHA) FROM tbUsuario WHERE USU_SENHA = @SENHA_CRIPTO_DIGITADA AND USU_LOGIN = @USU_LOGIN)
			IF(@TESTE_SENHA = 0)							
				SET @RETORNO = 0			
			ELSE 
				SET @RETORNO = 1
		END
		SELECT @RETORNO
		RETURN

	/*
       -se for igual a -1 usuario não cadastrado
       -se for igual a  0 senha invalida
       -se for igual a  1 vai logar
       */	
END
GO

--CARGA DE DADOS INICIAIS

INSERT INTO tbSetor (STR_ID, STR_DESCRICAO) VALUES (1, 'Gerência')
	INSERT INTO tbSetor (STR_ID, STR_DESCRICAO) VALUES (2, 'Financeiro')
	INSERT INTO tbSetor (STR_ID, STR_DESCRICAO) VALUES (3, 'Tecnologia')
	INSERT INTO tbSetor (STR_ID, STR_DESCRICAO) VALUES (4, 'Marketing')

	--Inserts tbNivelCargo
	INSERT INTO tbNivelCargo (NIC_ID, NIC_DESCRICAO) VALUES (1,'Estagiário(a)')
	INSERT INTO tbNivelCargo (NIC_ID, NIC_DESCRICAO) VALUES (2,'Júnior')
	INSERT INTO tbNivelCargo (NIC_ID, NIC_DESCRICAO) VALUES (3,'Pleno(a)')
	INSERT INTO tbNivelCargo (NIC_ID, NIC_DESCRICAO) VALUES (4,'Sênior')
	INSERT INTO tbNivelCargo (NIC_ID, NIC_DESCRICAO) VALUES (5,'Líder')

	--Inserts tbPerfilUsuario
	INSERT INTO tbPerfilUsuario (PFU_ID, PFU_DESCRICAO) VALUES (1, 'Administrador')
	INSERT INTO tbPerfilUsuario (PFU_ID, PFU_DESCRICAO) VALUES (2, 'Operacional 1')

	--Inserts tbFuncionario
SET IDENTITY_INSERT tbFuncionario ON
	INSERT INTO tbFuncionario (FUN_ID, FUN_NOME, FUN_CARGO, FUN_DATA_ADMISSAO, FUN_CPF, FUN_SALARIO, NIC_ID, STR_ID) 
	VALUES (1, 'Bruno de Sousa'		, 'Desenvolvedor C#'		, CONVERT(datetime,	'2021-04-08 00:00:00.000'), '172.977.640-00', 6000.50, 3, 1)

	INSERT INTO tbFuncionario (FUN_ID, FUN_NOME, FUN_CARGO, FUN_DATA_ADMISSAO, FUN_CPF, FUN_SALARIO, NIC_ID, STR_ID) 
	VALUES (2,	'Bruce Wayne'		, 'Contador'				, CONVERT(datetime, '2018-04-11 08:00:00.000'),	'633.230.430-81', 9500.55, 4, 2)

	INSERT INTO tbFuncionario (FUN_ID, FUN_NOME, FUN_CARGO, FUN_DATA_ADMISSAO, FUN_CPF, FUN_SALARIO, NIC_ID, STR_ID) 
	VALUES (3,	'Tony Stark'		, 'Arquiteto de Software'	, CONVERT(datetime, '2015-05-11 09:00:00.000'),	'439.340.130-15', 12000.85, 5, 1)

	INSERT INTO tbFuncionario (FUN_ID, FUN_NOME, FUN_CARGO, FUN_DATA_ADMISSAO, FUN_CPF, FUN_SALARIO, NIC_ID, STR_ID) 
	VALUES (4,	'Bill Gates'		, 'Desenvolvedor C#'		, CONVERT(datetime, '2020-04-11 06:00:00.000'),	'510.785.280-71', 8650.00, 4, 1)
SET IDENTITY_INSERT tbFuncionario OFF

--Inserts tbUsuario
	INSERT INTO tbUsuario (USU_LOGIN, USU_SENHA,PFU_ID, FUN_ID) 
	VALUES ('admin',		HASHBYTES('SHA2_256', CONVERT(varbinary(256), CAST('admin' AS binary(8))))		,1,1)

	INSERT INTO tbUsuario (USU_LOGIN, USU_SENHA,PFU_ID, FUN_ID) 
	VALUES ('bruce@wayne',	HASHBYTES('SHA2_256', CONVERT(varbinary(256), CAST('12345678' AS binary(8))))	,1,2)

	INSERT INTO tbUsuario (USU_LOGIN, USU_SENHA,PFU_ID, FUN_ID) 
	VALUES ('tony@stark',	HASHBYTES('SHA2_256', CONVERT(varbinary(256), CAST('654321' AS binary(8))))		,1,3)






